[project]
name = "3d-physarum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "numpy-stl>=3.2.0",
    "scikit-image>=0.20.0",
    "trimesh>=3.15.0",
    "scipy>=1.10.0",
    "pillow>=10.0.0",
    "fastapi>=0.115.14",
    "uvicorn>=0.34.3",
    "websockets>=15.0.1",
    "python-multipart>=0.0.20",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]

[tool.uv.workspace]
members = [
    "physarum-core",
    "web/backend", 
    "cli"
]
