[project]
name = "3d-physarum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "numpy-stl>=3.2.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
