[[commands]]
name="verify"
action = { function = "verify", params = { disabled_identifiers = [] } }

[[commands]]
name="pytest-imbue_cli"
action = { function = "pytest", params = { tests_path = "imbue_cli" } }
description = "Execute pytest for the Imbue CLI project."

[[commands]]
name="pytest-sculptor_v0"
action = { function = "pytest", params = { tests_path = "sculptor_v0" } }
description = "Execute pytest for the Sculptor_v0 project."

[[commands]]
name="echo-testing"
action = { function = "echo", params = { config_param = "configuration from file" } }
